leveldb.dbname=/tmp/ycsb-leveldb
leveldb.format=single
leveldb.destroy=false
leveldb.sync=false
leveldb.binary_key=false
leveldb.batch_size=64

leveldb.write_buffer_size=268435456
leveldb.max_file_size=268435456
leveldb.max_open_files=5000
leveldb.compression=no
leveldb.cache_size=536870912
leveldb.filter_bits=10
leveldb.block_size=16384
leveldb.block_restart_interval=16
